import { NextResponse } from 'next/server';
import { createServiceRoleClient, getAuthedUser } from '@loyalty-os/lib/server';
import { createServerSupabaseClient } from '@loyalty-os/lib/server';

function toCSV(rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return '';
  const headers = Object.keys(rows[0]);
  const escape = (v: unknown): string => {
    const s = v == null ? '' : String(v);
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"`
      : s;
  };
  const lines = [
    headers.join(','),
    ...rows.map((r) => headers.map((h) => escape(r[h])).join(',')),
  ];
  return lines.join('\n');
}

export async function GET() {
  try {
    const user = await getAuthedUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const supabase = await createServerSupabaseClient();
    const service = createServiceRoleClient();

    // Resolve tenant
    const { data: tenant } = await supabase
      .from('tenants')
      .select('id, business_name')
      .eq('auth_user_id', user.id)
      .is('deleted_at', null)
      .single();

    if (!tenant) return NextResponse.json({ error: 'Tenant not found' }, { status: 404 });

    const tid = tenant.id;

    // Fetch all data in parallel
    const [members, transactions, redemptions, rewards, campaigns] = await Promise.all([
      service
        .from('members')
        .select('id, name, email, phone, points_balance, tier, status, member_code, created_at, last_visit_at')
        .eq('tenant_id', tid)
        .is('deleted_at', null)
        .order('created_at', { ascending: true }),

      service
        .from('transactions')
        .select('id, member_id, points, balance_after, type, description, reference_id, created_at')
        .eq('tenant_id', tid)
        .order('created_at', { ascending: true }),

      service
        .from('redemptions')
        .select('id, member_id, reward_id, points_spent, status, alphanumeric_code, created_at, used_at, expires_at')
        .eq('tenant_id', tid)
        .order('created_at', { ascending: true }),

      service
        .from('rewards')
        .select('id, name, description, points_required, is_active, max_redemptions, redemption_count, valid_from, valid_until, created_at')
        .eq('tenant_id', tid)
        .is('deleted_at', null)
        .order('created_at', { ascending: true }),

      service
        .from('campaigns')
        .select('id, name, type, status, scheduled_at, sent_count, created_at')
        .eq('tenant_id', tid)
        .order('created_at', { ascending: true }),
    ]);

    const exportDate = new Date().toISOString().split('T')[0];
    const businessSlug = tenant.business_name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

    const sections = [
      `# LoyaltyOS Data Export`,
      `# Business: ${tenant.business_name}`,
      `# Date: ${exportDate}`,
      `# Generated by: LoyalBase LLC`,
      '',
      '## MEMBERS',
      toCSV((members.data ?? []) as Record<string, unknown>[]),
      '',
      '## TRANSACTIONS',
      toCSV((transactions.data ?? []) as Record<string, unknown>[]),
      '',
      '## REDEMPTIONS',
      toCSV((redemptions.data ?? []) as Record<string, unknown>[]),
      '',
      '## REWARDS',
      toCSV((rewards.data ?? []) as Record<string, unknown>[]),
      '',
      '## CAMPAIGNS',
      toCSV((campaigns.data ?? []) as Record<string, unknown>[]),
    ];

    const csv = sections.join('\n');
    const filename = `loyaltyos-export-${businessSlug}-${exportDate}.csv`;

    return new NextResponse(csv, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
