-- ─── ENTERPRISE GAMIFICATION ENGINE ────────────────────────────────────────
-- Migration: behavior scoring, missions, multipliers, leaderboard, interventions
-- Run after: 20260404000001_gamification.sql

-- ─── ENUMS ──────────────────────────────────────────────────────────────────
CREATE TYPE motivation_type AS ENUM ('achiever', 'socializer', 'explorer', 'competitor');
CREATE TYPE intervention_status AS ENUM ('pending', 'sent', 'dismissed', 'converted');
CREATE TYPE multiplier_condition AS ENUM (
  'always', 'tier_bronze', 'tier_silver', 'tier_gold', 'tier_platinum',
  'new_member', 'at_risk'
);

-- ─── 1. MEMBER BEHAVIOR SCORES ──────────────────────────────────────────────
-- One row per member; upserted by the scoring engine on each run.
CREATE TABLE member_behavior_scores (
  id               uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  member_id        uuid NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  churn_score      numeric(4,3) NOT NULL DEFAULT 0
                   CHECK (churn_score BETWEEN 0 AND 1),
  engagement_score numeric(4,3) NOT NULL DEFAULT 0
                   CHECK (engagement_score BETWEEN 0 AND 1),
  motivation_type  motivation_type NOT NULL DEFAULT 'achiever',
  visit_velocity   numeric(6,2) NOT NULL DEFAULT 0,   -- avg visits per 30 days
  points_velocity  numeric(10,2) NOT NULL DEFAULT 0,  -- avg points earned per 30 days
  days_since_visit integer NOT NULL DEFAULT 0,
  scored_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT unique_member_score UNIQUE (member_id)
);

-- ─── 2. MISSIONS ────────────────────────────────────────────────────────────
-- Multi-step challenge sequences authored by the tenant.
CREATE TABLE missions (
  id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name         text NOT NULL,
  description  text,
  bonus_points integer NOT NULL DEFAULT 0 CHECK (bonus_points >= 0),
  badge_id     uuid REFERENCES badges(id) ON DELETE SET NULL,
  starts_at    timestamptz,
  ends_at      timestamptz,
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- ─── 3. MISSION STEPS ───────────────────────────────────────────────────────
-- Ordered list of challenges that form a mission.
CREATE TABLE mission_steps (
  id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  mission_id   uuid NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
  challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  step_order   integer NOT NULL DEFAULT 1,
  CONSTRAINT unique_mission_step UNIQUE (mission_id, step_order)
);

-- ─── 4. MEMBER MISSION PROGRESS ─────────────────────────────────────────────
CREATE TABLE member_mission_progress (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  member_id       uuid NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  mission_id      uuid NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
  steps_completed integer NOT NULL DEFAULT 0 CHECK (steps_completed >= 0),
  completed_at    timestamptz,
  bonus_awarded   boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT unique_member_mission UNIQUE (member_id, mission_id)
);

-- ─── 5. POINT MULTIPLIERS ───────────────────────────────────────────────────
-- Time-boxed multiplier events. Engine applies the highest active multiplier
-- that matches the member's condition on each visit.
CREATE TABLE point_multipliers (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name        text NOT NULL,
  multiplier  numeric(4,2) NOT NULL DEFAULT 2.0 CHECK (multiplier > 1),
  condition   multiplier_condition NOT NULL DEFAULT 'always',
  starts_at   timestamptz NOT NULL,
  ends_at     timestamptz NOT NULL,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at > starts_at)
);

-- ─── 6. LEADERBOARD SNAPSHOTS ───────────────────────────────────────────────
-- Periodic snapshots generated by the engine (monthly/weekly).
-- entries = [{rank, member_id, name, avatar_url, points, tier, delta}]
CREATE TABLE leaderboard_snapshots (
  id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  period_key   text NOT NULL,  -- e.g. '2026-04' or '2026-W14'
  period_type  text NOT NULL CHECK (period_type IN ('month', 'week')),
  entries      jsonb NOT NULL DEFAULT '[]',
  generated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT unique_tenant_period UNIQUE (tenant_id, period_key, period_type)
);

-- ─── 7. ENGINE ACTIVITY LOG ─────────────────────────────────────────────────
-- Append-only audit log of every engine invocation and notable event.
CREATE TABLE engine_activity_log (
  id               uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id        uuid REFERENCES tenants(id) ON DELETE SET NULL,
  event_type       text NOT NULL,
  -- 'scoring_run' | 'intervention_triggered' | 'multiplier_applied'
  -- | 'mission_completed' | 'leaderboard_generated' | 'dynamic_challenge_created'
  payload          jsonb NOT NULL DEFAULT '{}',
  members_affected integer NOT NULL DEFAULT 0,
  duration_ms      integer,
  created_at       timestamptz NOT NULL DEFAULT now()
);

-- ─── 8. CHURN INTERVENTIONS ─────────────────────────────────────────────────
-- One record per triggered intervention; tracks resolution lifecycle.
CREATE TABLE churn_interventions (
  id                uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  member_id         uuid NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  churn_score       numeric(4,3) NOT NULL,
  intervention_type text NOT NULL,
  -- 'bonus_offer' | 'personal_challenge' | 'tier_reminder' | 'win_back_campaign'
  status            intervention_status NOT NULL DEFAULT 'pending',
  triggered_at      timestamptz NOT NULL DEFAULT now(),
  resolved_at       timestamptz,
  metadata          jsonb NOT NULL DEFAULT '{}'
);

-- ─── 9. DYNAMIC CHALLENGES ──────────────────────────────────────────────────
-- Engine-generated personalized challenges per member.
-- Distinct from tenant-authored challenges in the challenges table.
CREATE TABLE dynamic_challenges (
  id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  member_id     uuid NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  name          text NOT NULL,
  description   text,
  type          challenge_type NOT NULL,
  goal_value    integer NOT NULL CHECK (goal_value > 0),
  bonus_points  integer NOT NULL DEFAULT 0 CHECK (bonus_points >= 0),
  current_value integer NOT NULL DEFAULT 0,
  expires_at    timestamptz NOT NULL,
  completed_at  timestamptz,
  is_dismissed  boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ─── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE member_behavior_scores  ENABLE ROW LEVEL SECURITY;
ALTER TABLE missions                ENABLE ROW LEVEL SECURITY;
ALTER TABLE mission_steps           ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_mission_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE point_multipliers       ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_snapshots   ENABLE ROW LEVEL SECURITY;
ALTER TABLE engine_activity_log     ENABLE ROW LEVEL SECURITY;
ALTER TABLE churn_interventions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE dynamic_challenges      ENABLE ROW LEVEL SECURITY;

-- Tenant staff: full access to their own rows
CREATE POLICY "tenant_behavior_scores_rls" ON member_behavior_scores
  USING (tenant_id = auth_tenant_id());

CREATE POLICY "tenant_missions_rls" ON missions
  USING (tenant_id = auth_tenant_id());

CREATE POLICY "tenant_mission_steps_rls" ON mission_steps
  USING (mission_id IN (SELECT id FROM missions WHERE tenant_id = auth_tenant_id()));

CREATE POLICY "tenant_mission_progress_rls" ON member_mission_progress
  USING (tenant_id = auth_tenant_id());

CREATE POLICY "tenant_multipliers_rls" ON point_multipliers
  USING (tenant_id = auth_tenant_id());

CREATE POLICY "tenant_leaderboard_rls" ON leaderboard_snapshots
  USING (tenant_id = auth_tenant_id());

CREATE POLICY "tenant_engine_log_rls" ON engine_activity_log
  USING (tenant_id = auth_tenant_id());

CREATE POLICY "tenant_interventions_rls" ON churn_interventions
  USING (tenant_id = auth_tenant_id());

CREATE POLICY "tenant_dynamic_challenges_rls" ON dynamic_challenges
  USING (tenant_id = auth_tenant_id());

-- Members: read their own scores, missions, dynamic challenges
CREATE POLICY "member_scores_self_read" ON member_behavior_scores
  FOR SELECT USING (member_id = auth_member_id());

CREATE POLICY "member_mission_progress_self_read" ON member_mission_progress
  FOR SELECT USING (member_id = auth_member_id());

CREATE POLICY "member_dynamic_challenges_self_read" ON dynamic_challenges
  FOR SELECT USING (member_id = auth_member_id());

-- Members: read active missions and multipliers for their tenant
CREATE POLICY "member_missions_read" ON missions
  FOR SELECT USING (is_active = true);

CREATE POLICY "member_multipliers_read" ON point_multipliers
  FOR SELECT USING (is_active = true AND now() BETWEEN starts_at AND ends_at);

CREATE POLICY "member_leaderboard_read" ON leaderboard_snapshots
  FOR SELECT USING (tenant_id = auth_tenant_id());

-- ─── INDEXES ────────────────────────────────────────────────────────────────
CREATE INDEX idx_behavior_scores_tenant     ON member_behavior_scores(tenant_id);
CREATE INDEX idx_behavior_scores_churn      ON member_behavior_scores(tenant_id, churn_score DESC);
CREATE INDEX idx_behavior_scores_scored_at  ON member_behavior_scores(scored_at DESC);

CREATE INDEX idx_missions_tenant            ON missions(tenant_id, is_active);
CREATE INDEX idx_mission_steps_mission      ON mission_steps(mission_id, step_order);
CREATE INDEX idx_mission_progress_member    ON member_mission_progress(member_id);
CREATE INDEX idx_mission_progress_mission   ON member_mission_progress(mission_id);

CREATE INDEX idx_multipliers_tenant_active  ON point_multipliers(tenant_id, is_active, starts_at, ends_at);

CREATE INDEX idx_leaderboard_tenant_period  ON leaderboard_snapshots(tenant_id, period_type, period_key DESC);

CREATE INDEX idx_engine_log_tenant          ON engine_activity_log(tenant_id, created_at DESC);
CREATE INDEX idx_engine_log_event_type      ON engine_activity_log(event_type, created_at DESC);

CREATE INDEX idx_interventions_tenant       ON churn_interventions(tenant_id, status);
CREATE INDEX idx_interventions_member       ON churn_interventions(member_id, triggered_at DESC);

CREATE INDEX idx_dynamic_challenges_member  ON dynamic_challenges(member_id, expires_at);
CREATE INDEX idx_dynamic_challenges_tenant  ON dynamic_challenges(tenant_id, created_at DESC);

-- ─── UPDATED_AT TRIGGERS ────────────────────────────────────────────────────
-- Reuse set_updated_at() defined in the gamification migration.

CREATE TRIGGER missions_updated_at
  BEFORE UPDATE ON missions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER member_mission_progress_updated_at
  BEFORE UPDATE ON member_mission_progress
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── PG_CRON JOBS ───────────────────────────────────────────────────────────
-- Requires the pg_cron extension (enabled by default on Supabase Pro+).
-- These jobs call the run-scoring-engine edge function via pg_net.
-- Replace <PROJECT_REF> and <ANON_KEY> with actual Supabase project values,
-- or use vault secrets: select vault.decrypt_secret('scoring_anon_key')

-- Job 1: Score all members every 6 hours
SELECT cron.schedule(
  'enterprise-scoring-run',
  '0 */6 * * *',
  $$
  SELECT net.http_post(
    url := 'https://<PROJECT_REF>.supabase.co/functions/v1/run-scoring-engine',
    headers := '{"Content-Type": "application/json", "Authorization": "Bearer <ANON_KEY>"}'::jsonb,
    body := '{"trigger": "cron"}'::jsonb
  );
  $$
);

-- Job 2: Generate weekly leaderboard snapshots every Monday at 01:00 UTC
SELECT cron.schedule(
  'enterprise-leaderboard-weekly',
  '0 1 * * 1',
  $$
  SELECT net.http_post(
    url := 'https://<PROJECT_REF>.supabase.co/functions/v1/run-scoring-engine',
    headers := '{"Content-Type": "application/json", "Authorization": "Bearer <ANON_KEY>"}'::jsonb,
    body := '{"trigger": "cron", "tasks": ["leaderboard_weekly"]}'::jsonb
  );
  $$
);

-- Job 3: Generate monthly leaderboard snapshots on the 1st of each month at 01:30 UTC
SELECT cron.schedule(
  'enterprise-leaderboard-monthly',
  '30 1 1 * *',
  $$
  SELECT net.http_post(
    url := 'https://<PROJECT_REF>.supabase.co/functions/v1/run-scoring-engine',
    headers := '{"Content-Type": "application/json", "Authorization": "Bearer <ANON_KEY>"}'::jsonb,
    body := '{"trigger": "cron", "tasks": ["leaderboard_monthly"]}'::jsonb
  );
  $$
);
